SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;



DROP ROLE if exists "CATASTO_ROLE";

CREATE ROLE "CATASTO_ROLE"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

DROP ROLE if exists "PROMA_ROLE";

CREATE ROLE "PROMA_ROLE"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


DROP ROLE if exists catasto_dati;

CREATE ROLE catasto_dati LOGIN
  ENCRYPTED PASSWORD 'md50da066e90e3caa1e4ea8829fdf80725c'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "CATASTO_ROLE" TO catasto_dati;


DROP ROLE if exists catasto_metadati;

CREATE ROLE catasto_metadati LOGIN
  ENCRYPTED PASSWORD 'md5c5aec0e3f617a36024d8cc64071c8eb5'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "CATASTO_ROLE" TO catasto_metadati;

DROP ROLE if exists city4_data;

CREATE ROLE city4_data LOGIN
  ENCRYPTED PASSWORD 'md595302cc2667b7ce202522d5ae7aa0e13'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "PROMA_ROLE" TO city4_data;

DROP ROLE city4_metadata;

CREATE ROLE city4_metadata LOGIN
  ENCRYPTED PASSWORD 'md59212412a1ea3b9dfff9d6c6242bea4fe'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "PROMA_ROLE" TO city4_metadata;


